<a href="https://colab.research.google.com/github/24f3003058/Machine-Learning-Practice/blob/main/Another_copy_of_Practice_OPE_(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ⚠️ Important Notice:

These questions are **meant for practice purposes only**. They **do not** represent the actual OPPE paper pattern, question style, or any official material.
Please avoid memorizing the question patterns or the exact code solutions.

Instead, focus on developing the skill to **tackle unfamiliar problems** — explore library documentation, understand concepts, and learn how to apply them in new contexts.


Regards\
MLT TAs

# Data Preprocessing

[click here for dataset](https://drive.google.com/file/d/1_kxlGz-Ml4tcDdGFyZLf8PwpKvpr1q-v/view?usp=drivesdk)

## Q1. Which dataset are you using for this exam?
- V1
- V2
- V3
- V4
- V5

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("dataset.csv")

## Q2. How many total number of rows and columns are there in the dataset?
- Rows:2000 , Columns: 15
- Rows:20000 , Columns: 14
- Rows:20000 , Columns: 16
- Rows:20000 , Columns: 15

\

Answer: D

In [2]:
df.shape

(20000, 15)

## Q3. Is there any Missing values in the given dataset ?
- Yes
- No

\

Answer: Yes

In [3]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
IncomeGroup       0
dtype: int64

In [4]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,IncomeGroup
0,62,Self-emp-not-inc,26911,7th-8th,4,Widowed,Other-service,Not-in-family,White,Female,0,0,66,United-States,<=50K
1,18,Private,208103,11th,7,Never-married,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
2,25,Private,102476,Bachelors,13,Never-married,Farming-fishing,Own-child,White,Male,27828,0,50,United-States,>50K
3,33,Private,511517,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
4,36,Private,292570,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,26,Private,62438,Bachelors,13,Married-civ-spouse,Sales,Wife,White,Female,0,0,40,United-States,>50K
19996,62,Private,57970,7th-8th,4,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
19997,31,Private,137290,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,55,United-States,>50K
19998,25,Private,29020,Assoc-acdm,12,Divorced,Adm-clerical,Not-in-family,Black,Female,0,0,45,United-States,<=50K
19999,55,Private,256953,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,Black,Female,0,0,44,United-States,<=50K

## Q4. Check all " ?" symbol in the dataset and replace it with "np.nan" value . Which of the columns in the dataset have null values?
- age
- native-country
- capital-gain
- workclass
- occupation
- None of these

\


Answer: B, D, E

In [5]:
df["age"].unique()

array([62, 18, 25, 33, 36, 34, 43, 47, 29, 23, 19, 31, 59, 35, 41, 54, 30,
       21, 38, 53, 27, 37, 45, 22, 60, 39, 48, 57, 64, 28, 49, 40, 61, 56,
       24, 26, 58, 51, 46, 75, 32, 68, 65, 44, 55, 42, 52, 76, 50, 67, 74,
       66, 20, 72, 17, 73, 63, 77, 71, 79, 69, 70, 90, 78, 82, 80, 83, 84,
       81, 85])

In [6]:
df["native-country"].unique()

array([' United-States', ' ?', ' Cuba', ' Mexico', ' Taiwan', ' India',
       ' Ecuador', ' Italy', ' Philippines', ' China', ' Canada',
       ' England', ' Honduras', ' South', ' Puerto-Rico', ' El-Salvador',
       ' Jamaica', ' France', ' Guatemala', ' Germany', ' Iran',
       ' Poland', ' Ireland', ' Japan', ' Peru', ' Cambodia', ' Laos',
       ' Haiti', ' Columbia', ' Nicaragua', ' Vietnam', ' Hong',
       ' Outlying-US(Guam-USVI-etc)', ' Hungary', ' Yugoslavia',
       ' Dominican-Republic', ' Portugal', ' Trinadad&Tobago',
       ' Scotland', ' Thailand', ' Greece', ' Holand-Netherlands'],
      dtype=object)

In [7]:
df["native-country"]=df["native-country"].replace(" ?",np.nan)

In [8]:
df['native-country'].unique()

array([' United-States', nan, ' Cuba', ' Mexico', ' Taiwan', ' India',
       ' Ecuador', ' Italy', ' Philippines', ' China', ' Canada',
       ' England', ' Honduras', ' South', ' Puerto-Rico', ' El-Salvador',
       ' Jamaica', ' France', ' Guatemala', ' Germany', ' Iran',
       ' Poland', ' Ireland', ' Japan', ' Peru', ' Cambodia', ' Laos',
       ' Haiti', ' Columbia', ' Nicaragua', ' Vietnam', ' Hong',
       ' Outlying-US(Guam-USVI-etc)', ' Hungary', ' Yugoslavia',
       ' Dominican-Republic', ' Portugal', ' Trinadad&Tobago',
       ' Scotland', ' Thailand', ' Greece', ' Holand-Netherlands'],
      dtype=object)

capital-gain
workclass
occupation
None of these

In [9]:
df["capital-gain"].unique()

array([    0, 27828,  4508, 15024,  3674,  7688, 14344,  1471, 99999,
        2829,  1409,  2977,  4865, 14084,  3887,  2105,  2174,  2176,
        4650,  6723,  6497,  4416, 20051,  3325,  2597,  2354,  9386,
       25124, 10520,  7298,  1797,  3103,  6767,  1151,  2961,  2653,
        3464,  5178, 13550,  3137,   594,  4787,   914,  2907,  3908,
        2202,  1055,  5013,   114,  3432, 10605,  8614,  2635,  4064,
        1848,  1506,  3942,  5556,  7443,  3411,  4101,  2329,  2463,
        2885, 25236,  9562,  3471,  6849, 15020,  4386,  2407,  7430,
       15831,  1831,  1639,  5455,  2228,  2964,  3818, 10566,  2050,
        2036,  2580, 18481,  3781,  1424,  1455,  5721,  6360,  2414,
        6418, 34095, 11678,  3273,  4934,  2346,  2009,  3418,  3456,
        7896,  6514,   991,  2290,  4687,  2993, 41310,  2062,  1086,
        2936, 22040,  1173,  5060,  4931])

In [10]:
df["workclass"].unique()

array([' Self-emp-not-inc', ' Private', ' Local-gov', ' Federal-gov',
       ' Self-emp-inc', ' ?', ' State-gov', ' Without-pay',
       ' Never-worked'], dtype=object)

In [11]:
df["workclass"]=df["workclass"].replace(" ?",np.nan)

In [12]:
df["workclass"].unique()

array([' Self-emp-not-inc', ' Private', ' Local-gov', ' Federal-gov',
       ' Self-emp-inc', nan, ' State-gov', ' Without-pay',
       ' Never-worked'], dtype=object)

In [13]:
df["occupation"].unique()

array([' Other-service', ' Farming-fishing', ' Prof-specialty',
       ' Machine-op-inspct', ' Handlers-cleaners', ' Exec-managerial',
       ' Adm-clerical', ' Craft-repair', ' Sales', ' Transport-moving',
       ' ?', ' Tech-support', ' Priv-house-serv', ' Protective-serv',
       ' Armed-Forces'], dtype=object)

In [14]:
df["occupation"]=df["occupation"].replace(" ?",np.nan)

In [15]:
df["occupation"].unique()

array([' Other-service', ' Farming-fishing', ' Prof-specialty',
       ' Machine-op-inspct', ' Handlers-cleaners', ' Exec-managerial',
       ' Adm-clerical', ' Craft-repair', ' Sales', ' Transport-moving',
       nan, ' Tech-support', ' Priv-house-serv', ' Protective-serv',
       ' Armed-Forces'], dtype=object)

## Q5. What fraction of total samples (in percentage) have missing value in occupation column?

\
Answer: 5.7%

In [16]:
df["occupation"].isnull().sum()

np.int64(1140)

In [17]:
df["occupation"].shape

(20000,)

In [18]:
1140/20000*100

5.7

## Q6. What fraction of total samples(In percentage) have income <= 50k in the given dataset? (round the value upto 2 decimal places)
- 75.95
- 75.83
- 76.51
- 72.82
- 76.00



Answer: C

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             20000 non-null  int64
 1   workclass       18863 non-null  object
 2   fnlwgt          20000 non-null  int64
 3   education       20000 non-null  object
 4   education-num   20000 non-null  int64
 5   marital-status  20000 non-null  object
 6   occupation      18860 non-null  object
 7   relationship    20000 non-null  object
 8   race            20000 non-null  object
 9   sex             20000 non-null  object
 10  capital-gain    20000 non-null  int64
 11  capital-loss    20000 non-null  int64
 12  hours-per-week  20000 non-null  int64
 13  native-country  19646 non-null  object
 14  IncomeGroup     20000 non-null  object
dtypes: int64(6), object(9)
memory usage: 2.3+ MB

In [20]:
df["IncomeGroup"].unique()

array([' <=50K', ' >50K'], dtype=object)

In [21]:
fraction = len(df[df['IncomeGroup'] == ' <=50K']) / len(df) * 100
print(round(fraction, 2))

76.51

In [22]:
fraction = df['IncomeGroup'].value_counts(normalize=True)[' <=50K'] * 100
print(round(fraction, 2))

76.51

In [23]:
14018/20000

0.7009

## Q7: What is the mean age of the samples given in the dataset(mark the closest integer from the given options)?
- 25
- 34
- 38
- 45
- 50

\

Answer: C

In [24]:
df["age"].mean()

np.float64(38.553)

## Q8: How many people have completed their education upto "Preschool" only ?
- 29
- 32
- 26
- 27

\

Answer: B

In [25]:
df["education"].unique()

array([' 7th-8th', ' 11th', ' Bachelors', ' HS-grad', ' Some-college',
       ' Masters', ' Assoc-voc', ' Doctorate', ' 5th-6th', ' 10th',
       ' 12th', ' Assoc-acdm', ' Prof-school', ' 9th', ' 1st-4th',
       ' Preschool'], dtype=object)

In [26]:
df[df['education']==" Preschool"].shape

(32, 15)

## Q9. What is the correlation cofficient between column "education-num" and column "capital-gain" ?

\

Answer: 0.12

In [27]:
df["education-num"].corr(df["capital-gain"])

np.float64(0.12456727883397226)

## Apply SimpleImputer with strategy = 'most_frequent' to replace all NaN value by mode of respective column in the original dataset.(Use this updated dataset only for all further questions)

## Q10. What is the mode of 'occupation' column of updated datset?
- Adm-clerical
- Prof-specialty
- Exec-managerial
- Craft-repair
- Private

\

Answer: B

In [28]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
df_imputed=pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
#we need to mpute all columns

## Split the dataset into X1, X2 and y, where X1 contains all Numerical features, X2 contains all categorical features(except "IncomeGroup") and save 'IncomeGroup' column in y variable. Then apply OneHotEncoder on the categorical features(X2) with option (sparse = False) and StandardScaler on the numerical features (X2).


## Q11. What is the total number of columns in X1 and X2 variables respectively?
- (6,9)
- (9,6)
- (6,8)
- (8,6)

\

Answer: C

In [29]:
X1=df.select_dtypes(exclude="object")
X2=df.select_dtypes(include="object").drop(columns='IncomeGroup')
y=df["IncomeGroup"]

In [30]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
X2_ohe=ohe.fit_transform(X2)

In [31]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X1_scaled=scaler.fit_transform(X1)

In [32]:
X1.shape

(20000, 6)

In [33]:
X2.shape

(20000, 8)

## Apply StandardScaler on the X1 data and OneHotEncoder on X2 data with option (sparse = False).

## Q12. What are the data types of X1 and X2?
- dataframe, dataframe
- dataframe, numpy array
- dense scipy array, numpy array
- numpy array, numpy array

\

Answer: D

In [34]:
type(X1_scaled)

numpy.ndarray

In [35]:
type(X2_ohe)

numpy.ndarray

## Concatenate X1 and X2 and call it X( Keep axis = 1) and then Convert X to a dataframe.
## Q13. What is the new shape of resultant X?

- (20000, 105)
- (20000, 204)
- (20000, 14)
- (2000, 98)

\

Answer: A

In [36]:
X=np.concatenate([X1_scaled,X2_ohe],axis=1)
X=pd.DataFrame(X)
X.shape

(20000, 108)

# Model Building

Make use of your preprocessed data that you got from above preprocessing steps.

Note: In current OPPE setup you will be given the preprocessed dataset for Model Building.

## Q14. Split the dataset into training and validation dataset into 80:20 ratio while keeping random_state =64. what is the shape of the y_train dataset?
- (20000,)
- (16000, 15)
- (20000, 14)
- (4000, 98)
- (16000,)


\

Answer: D

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=64)
y_train.shape

(16000,)

## Instantiate a perceptron classifier that with following parameters:
- Fit the intercept
- Put warm start to be False

## Fit this perceptron model with the training dataset and calculate the accuracy score for training data.
## Q15: Which of the following option matches with the score?
- 0.8130625
- 0.8379375
- 0.8239375
- 0.8058125
- 0.78475


\

Answer: A

In [38]:
from sklearn.linear_model import Perceptron
p=Perceptron(fit_intercept=True,warm_start=False)
p.fit(X_train,y_train)

Perceptron()

In [39]:
p.score(X_train,y_train)

0.813125

## Q16. Create a new Perceptron(random_state=42) object with given settings in the instrunctions and train it on training set . What is the value of bias (intercept) (upto 1 decimal point) ?
- Set early stopping and fit intercept to be True
- Put warm start to be False


\

Answer: -8

In [40]:
new_p=Perceptron(random_state=42,fit_intercept=True,warm_start=False)
new_p=new_p.fit(X_train,y_train)

In [41]:
new_p.intercept_

array([-5.])

## Use SGDClassifier on the training dataset (X_train and y_train) to train the model. Use the following parameters:

- log is the loss function to be used
- apply ridge regularization,
- maximum number of passes over the training data is 10
- initial learning rate is 0.01,
- regularization rate value is 0.001,
- learning rate should not change during training.
- Take random_state=64.
- Set warm_state as False

Note : Please ignore the convergence warning.

## Q17. Based on this operation, calculate and enter the correct value of accuracy (Upto 4 decimal points).

ANS: (Type: Range) 0.840,0.855

In [42]:
from sklearn.linear_model import SGDClassifier
sgd=SGDClassifier(loss="log_loss",penalty='l2',alpha=0.001,max_iter=10,eta0=0.01,learning_rate="constant",random_state=64,warm_start=False)
sgd.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_stochastic_gradient.py:738: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

SGDClassifier(alpha=0.001, eta0=0.01, learning_rate='constant', loss='log_loss',
              max_iter=10, random_state=64)

In [43]:
sgd.score(X_train,y_train)

0.851125

## Take LogisticRegression estimator with following parameters for fitting on the training dataset:
- Use sag as solver
- Set random state to be equal to 64
- Tolerance for stopping criteria to be 1e-3
- Maximum number of iterations taken for the solvers to converge to be 100

##Q18. Enter the recall score you got for the given model (Take average as macro).

ANS: (Type: Range) 0.74,0.78

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score
lg=LogisticRegression(solver="sag",random_state=64,tol=1e-3,max_iter=100)
lg=lg.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [45]:
y_pred=lg.predict(X_train)
recall_score(y_train,y_pred,average="macro")

0.767586109587682

## Use Gridsearchcv with KNeighborsClassifier() being the estimator, accuracy as scoring parameter, cv value as 4 and consider [1,3,5,7] as "number of neighbors" to be examined.

## Consider following parameters for KNeighborsClassifier():
- Take metric as 'minkowski',
- Set P value as 2
- Keep other parameter values as default value.

## Q19. What is the best value of K you obtained using above instruction?


\

Answer: 7

In [46]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(metric="minkowski",p=2)
param_grid={'n_neighbors':[1,3,5,7]}
gscv=GridSearchCV(
    estimator=knn,
    param_grid=param_grid,
    scoring="accuracy",
    cv=4
)
gscv.fit(X_train,y_train)

GridSearchCV(cv=4, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7]}, scoring='accuracy')

In [47]:
gscv.best_params_

{'n_neighbors': 7}

In [48]:
gscv.best_score_

np.float64(0.833625)

#(Common Instruction for Q20 to Q23)
## Take DecisionTreeClassifier(random_state = 64) with GridSearchCV to train the model.Hyperparameter tuning to be done over the following parameters:
- Use criterion as 'entropy' or 'gini'
- Use splitter as 'random' or 'best'
- Use minimum number of samples per leaf as [2,4,6,8,10]
- Use maximum depth as [3,4,5,6]
- Use cross validation = 4

## Q20. Enter the value (up to 2 decimal points) of the 'score' on testing set using best model.


\

Answer: 0.84

In [52]:
from sklearn.tree import DecisionTreeClassifier
param_grid={
    "criterion":["entropy",'gini'],
    "splitter":['random','best'],
    "min_samples_leaf":[2,4,6,8,10],
    "max_depth":[3,4,5,6]
}
dtc=DecisionTreeClassifier(random_state=64 )
gscv=GridSearchCV(dtc,param_grid,cv=4)
gscv.fit(X_train,y_train)

GridSearchCV(cv=4, estimator=DecisionTreeClassifier(random_state=64),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [3, 4, 5, 6],
                         'min_samples_leaf': [2, 4, 6, 8, 10],
                         'splitter': ['random', 'best']})

In [54]:
gscv.score(X_test,y_test)

0.84975

## Q21. Enter the value of best max_depth of the model after training with GridSearchCV.


\

Answer: 6

In [55]:
gscv.best_params_

{'criterion': 'gini',
 'max_depth': 6,
 'min_samples_leaf': 10,
 'splitter': 'best'}

## Q22. Enter the value of best min_samples_leaf of the model after training with GridSearchCV.


\

Answer: 10

In [56]:
10

10

## Q23: What are the number of nodes in the optimal tree?


\

Answer: 75

In [61]:
gscv.best_estimator_.tree_.node_count

75

## Take RandomForestClassifier (random state to be 64) with GridSearchCV to tune the number of decision trees with training set. The number of trees in forest can range from 5 to 10 (both inclusive).
## Q24. Mark the number of decision trees that will produce the best score on the training data.
- 5
- 7
- 8
- 10
- 9
- 6


\

Answer: D

In [64]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=64)

param_grid={
    "n_estimators":[5,6,7,8,9,10]
}
gscv=GridSearchCV(rfc,param_grid)
gscv.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(random_state=64),
             param_grid={'n_estimators': [5, 6, 7, 8, 9, 10]})

In [68]:
gscv.best_score_

np.float64(0.8438125)

In [69]:
gscv.best_estimator_

RandomForestClassifier(n_estimators=10, random_state=64)

In [71]:
gscv.best_params_['n_estimators']

10

# (Common Instructions for Q25,Q26)

## Take an adaboost model with following hyperparameter values and tune it using GridsearchCV.
- Use n_estimators as [10,20,30]
- random_state = 64
- Use learning_rate as [0.5,1,2]
- Take cv value= 4

## Q25. Train the 'model' using above instructions and enter the 'accuracy score' (up to 3 decimal points) on the test data.


\

Answer: 0.85

In [75]:
from sklearn.ensemble import AdaBoostClassifier
adaa=AdaBoostClassifier(random_state=64)
param_grid={
    "n_estimators":[10,20,30],
    "learning_rate":[0.5,1,2]

}
gscv=GridSearchCV(adaa,param_grid,cv=4)
gscv.fit(X_train,y_train)

GridSearchCV(cv=4, estimator=AdaBoostClassifier(random_state=64),
             param_grid={'learning_rate': [0.5, 1, 2],
                         'n_estimators': [10, 20, 30]})

In [79]:
gscv.score(X_test,y_test)

0.85175

## Q26. Enter the value of best n_estimators of the model after training with GridSearchCV.


\

Answer: 30

In [80]:
gscv.best_estimator_

AdaBoostClassifier(learning_rate=1, n_estimators=30, random_state=64)

## Apply GridsearchCV and support vector machine (SVM)(kernel':('linear', 'rbf'), 'C':[1, 10]) on the training dataset X_train, y_train and calculate the best value of C and kernel.

## Q27. Which of the following options represent the best parameters. (Keep patience: It is common if it takes arround 5 min to complete the run.)

- {'C': 1, 'kernel': 'rbf'}
- {'C': 10, 'kernel': 'rbf'}
- {'C': 10, 'kernel': 'linear'}
- {'C': 1, 'kernel': 'linear'}
- None of these

\

Answer: A

In [88]:
from sklearn.svm import SVC
svc=SVC()

param_grid={
    'kernel':('linear','rbf'),
    'C':[1,10]
}
gscv=GridSearchCV(svc,param_grid)
gscv.fit(X_train,y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')})

In [90]:
gscv.best_estimator_

SVC(C=1)