OPPE2 Practice

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("T124OPPE1_Preprocessing5.csv")

In [3]:
df

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,0.339451,80.271980,2.166533,0.484391,8.0,20.0,11.355250,6,336.729137,22.540915,376.060450,6.969427,21.669087,NO
1,1.059730,1.909323,10.590647,0.755596,7.0,53.0,5.238639,5,277.033814,19.479797,395.990102,12.433205,26.237995,NO
2,1.307746,45.833665,4.222120,2.362586,8.0,41.0,4.776458,7,398.069607,15.228967,397.233472,6.777399,36.525943,NO
3,0.478246,0.433153,10.679947,1.458648,7.0,73.0,2.605083,9,432.777976,19.465542,339.411533,16.772050,21.628186,NO
4,9.141458,1.142936,19.280459,0.813295,8.0,99.0,3.117690,24,666.592484,22.056939,304.230845,19.517317,13.399126,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.888632,0.635426,18.327980,1.214383,7.0,100.0,3.268107,25,667.377709,21.213656,397.210534,21.537646,13.966395,NO
3996,1.485618,81.724553,5.754772,0.422434,8.0,29.0,5.300785,5,245.586194,20.083284,398.517120,3.603526,37.343527,NO
3997,1.515471,55.774211,4.055462,0.854897,7.0,29.0,7.274133,5,371.170011,18.166783,389.254112,5.526206,32.048290,NO
3998,1.213408,0.434945,8.364137,1.312692,6.0,87.0,4.874288,4,307.242745,22.455347,304.039084,16.896982,14.958820,NO
3999,0.208430,36.479194,6.629429,1.324817,6.0,29.0,8.640236,3,305.434860,17.848331,395.517130,12.591712,18.459617,NO

In [4]:
df.head

<bound method NDFrame.head of           CRIM         ZN      INDUS  POLINDEX   RM    AGE        DIS  \
0     0.339451  80.271980   2.166533  0.484391  8.0   20.0  11.355250
1     1.059730   1.909323  10.590647  0.755596  7.0   53.0   5.238639
2     1.307746  45.833665   4.222120  2.362586  8.0   41.0   4.776458
3     0.478246   0.433153  10.679947  1.458648  7.0   73.0   2.605083
4     9.141458   1.142936  19.280459  0.813295  8.0   99.0   3.117690
...        ...        ...        ...       ...  ...    ...        ...
3995  9.888632   0.635426  18.327980  1.214383  7.0  100.0   3.268107
3996  1.485618  81.724553   5.754772  0.422434  8.0   29.0   5.300785
3997  1.515471  55.774211   4.055462  0.854897  7.0   29.0   7.274133
3998  1.213408   0.434945   8.364137  1.312692  6.0   87.0   4.874288
3999  0.208430  36.479194   6.629429  1.324817  6.0   29.0   8.640236

      HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0                6  336.729137  22.540915  376.060450   6.969427  21.669087
1                5  277.033814  19.479797  395.990102  12.433205  26.237995
2                7  398.069607  15.228967  397.233472   6.777399  36.525943
3                9  432.777976  19.465542  339.411533  16.772050  21.628186
4               24  666.592484  22.056939  304.230845  19.517317  13.399126
...            ...         ...        ...         ...        ...        ...
3995            25  667.377709  21.213656  397.210534  21.537646  13.966395
3996             5  245.586194  20.083284  398.517120   3.603526  37.343527
3997             5  371.170011  18.166783  389.254112   5.526206  32.048290
3998             4  307.242745  22.455347  304.039084  16.896982  14.958820
3999             3  305.434860  17.848331  395.517130  12.591712  18.459617

     RIVERSIDE
0           NO
1           NO
2           NO
3           NO
4           NO
...        ...
3995        NO
3996        NO
3997        NO
3998        NO
3999        NO

[4000 rows x 14 columns]>

In [5]:
df.shape

(4000, 14)

In [7]:
df['PRICE'].mean()

np.float64(24.52924464570181)

In [13]:
df[df["RM"] >= 5].shape
df.query("RM >= 5").shape

(3925, 14)

In [16]:
df["PRICE"].sort_values(ascending=False).head(10).mean()
df["PRICE"].nlargest(10).mean()

np.float64(52.2033351761825)

In [25]:
df["RM"].isna().sum()

np.int64(0)

In [26]:
df["RM"].unique()

array([ 8.,  7.,  6., 10., -1., 11.,  5.,  9.,  4.])

In [27]:
df[df["RM"] == -1].shape

(68, 14)

In [32]:
df["AGE"].isna().sum()

np.int64(0)

In [33]:

df["AGE"].unique()

array([ 20.,  53.,  41.,  73.,  99.,   7., 101.,  17.,  77.,  81.,  91.,
        93., 100.,  59.,  96.,  32.,  97.,  34.,  89.,  40.,  23.,  18.,
        52.,  94.,  46.,  33.,  83.,   3.,  80.,  92.,  88.,  98.,  87.,
        35.,  78.,  55.,  90.,  44.,  70.,  85.,  67.,  75.,  71.,  74.,
        54.,  84.,  24.,  86.,  50.,  76.,  30.,  64.,  43., 102.,  -2.,
        39.,  11.,  60.,  16.,  28.,  56.,  29.,  69.,  49.,   8.,  61.,
        82.,   9.,  62.,  51.,  45.,  42.,  14.,  57.,  12.,  21.,  48.,
        95.,  38.,  58.,  47.,  36.,  63.,  27.,  26.,  22.,  72.,  79.,
        66.,  19.,   6.,  37.,  31.,  25.,  65.,  10.,  68.,  15.,   4.,
         5.])

In [35]:
df[df["AGE"] == -2].shape

(59, 14)

In [37]:
df["RIVERSIDE"].unique()

<StringArray>
['NO', 'YES', 'UNKNOWN']
Length: 3, dtype: str

In [38]:
df[df["RIVERSIDE"]=="UNKNOWN"].shape

(88, 14)

In [40]:
df["RIVERSIDE"].value_counts()

RIVERSIDE
NO         3628
YES         284
UNKNOWN      88
Name: count, dtype: int64

In [48]:
df[(df["RIVERSIDE"] =="YES")&(df["AGE"] <=50)].shape

(37, 14)

In [52]:
df[(df["HIGHWAYCOUNT"]==6) | (df["HIGHWAYCOUNT"]==7) |(df["HIGHWAYCOUNT"]==8)].shape

(1209, 14)

In [56]:
def category(price):
    if price<10:
        return "Category 1"
    elif 10<=price<20:
        return "Category 2"
    elif 20<=price<30:
        return "Category 3"
    elif 30<=price<40:
        return "Category 4"
    else:
        return "Category 5"

In [57]:
df["Category"]= df["PRICE"].apply(category)

In [58]:
df

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE,Category
0,0.339451,80.271980,2.166533,0.484391,8.0,20.0,11.355250,6,336.729137,22.540915,376.060450,6.969427,21.669087,NO,Category 3
1,1.059730,1.909323,10.590647,0.755596,7.0,53.0,5.238639,5,277.033814,19.479797,395.990102,12.433205,26.237995,NO,Category 3
2,1.307746,45.833665,4.222120,2.362586,8.0,41.0,4.776458,7,398.069607,15.228967,397.233472,6.777399,36.525943,NO,Category 4
3,0.478246,0.433153,10.679947,1.458648,7.0,73.0,2.605083,9,432.777976,19.465542,339.411533,16.772050,21.628186,NO,Category 3
4,9.141458,1.142936,19.280459,0.813295,8.0,99.0,3.117690,24,666.592484,22.056939,304.230845,19.517317,13.399126,NO,Category 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.888632,0.635426,18.327980,1.214383,7.0,100.0,3.268107,25,667.377709,21.213656,397.210534,21.537646,13.966395,NO,Category 2
3996,1.485618,81.724553,5.754772,0.422434,8.0,29.0,5.300785,5,245.586194,20.083284,398.517120,3.603526,37.343527,NO,Category 4
3997,1.515471,55.774211,4.055462,0.854897,7.0,29.0,7.274133,5,371.170011,18.166783,389.254112,5.526206,32.048290,NO,Category 4
3998,1.213408,0.434945,8.364137,1.312692,6.0,87.0,4.874288,4,307.242745,22.455347,304.039084,16.896982,14.958820,NO,Category 2
3999,0.208430,36.479194,6.629429,1.324817,6.0,29.0,8.640236,3,305.434860,17.848331,395.517130,12.591712,18.459617,NO,Category 2

In [59]:
df["Category"].value_counts()

Category
Category 3    1977
Category 2    1162
Category 4     534
Category 5     288
Category 1      39
Name: count, dtype: int64

# Apply preprocessing

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
# DATA REPLACEMENT
df["RM"]=df["RM"].replace(-1,np.nan)
df["RIVERSIDE"]=df["RIVERSIDE"].replace("UNKNOWN",np.nan)
df["AGE"]=df["AGE"].replace(-2,np.nan)

In [68]:
df.drop(columns=["Category"])

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,0.339451,80.271980,2.166533,0.484391,8.0,20.0,11.355250,6,336.729137,22.540915,376.060450,6.969427,21.669087,NO
1,1.059730,1.909323,10.590647,0.755596,7.0,53.0,5.238639,5,277.033814,19.479797,395.990102,12.433205,26.237995,NO
2,1.307746,45.833665,4.222120,2.362586,8.0,41.0,4.776458,7,398.069607,15.228967,397.233472,6.777399,36.525943,NO
3,0.478246,0.433153,10.679947,1.458648,7.0,73.0,2.605083,9,432.777976,19.465542,339.411533,16.772050,21.628186,NO
4,9.141458,1.142936,19.280459,0.813295,8.0,99.0,3.117690,24,666.592484,22.056939,304.230845,19.517317,13.399126,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.888632,0.635426,18.327980,1.214383,7.0,100.0,3.268107,25,667.377709,21.213656,397.210534,21.537646,13.966395,NO
3996,1.485618,81.724553,5.754772,0.422434,8.0,29.0,5.300785,5,245.586194,20.083284,398.517120,3.603526,37.343527,NO
3997,1.515471,55.774211,4.055462,0.854897,7.0,29.0,7.274133,5,371.170011,18.166783,389.254112,5.526206,32.048290,NO
3998,1.213408,0.434945,8.364137,1.312692,6.0,87.0,4.874288,4,307.242745,22.455347,304.039084,16.896982,14.958820,NO
3999,0.208430,36.479194,6.629429,1.324817,6.0,29.0,8.640236,3,305.434860,17.848331,395.517130,12.591712,18.459617,NO

In [70]:
X=df.drop(columns=["PRICE"])

In [71]:
y=df["PRICE"]

In [72]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [73]:
X_train.shape

(2800, 14)

In [74]:
X_test.shape

(1200, 14)